name: FrostScan CI

on: 
    push:
      branches: [main, dev]
    pull_request:

jobs:
  ci:
    name: ${{ matrix.os }} / check-test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
    
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install -y \
            libx11-dev \
            libwayland-dev \
            libxkbcommon-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev 

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check
        run: cargo check --all-targets

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --all-features --verbose
